### ISSUE TITLE
System.IO.Compression error

### ISSUE THREAD

**Issue by alfeg** [Blacklite/Ncapsulate#18]
It's not really an issue of this library. But mabe helpful for other people.

I've got an exception when try to install Ncapsulate package with error, that System.IO.Compression is not available.

This was a bug of old Microsoft.Bcl.Build package, and after updating I were able to install Ncapsulate without any issue.

**Comment by isochronous** [comment]
I ran into this same issue, and it's worth noting that there's a nuget package for System.IO.Compression, so a good fix might be to add it as a dependency for the Node package. If a user already has it, then it'll just skip over it, but if they don't, then it'll download and install it automatically instead of throwing an error and aborting.
